version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=app.config.LocalSettings
      - SECRET_KEY=secret
      - DATABASE_URL=http://dynamodb:8000
    depends_on:
      - dynamodb

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=development
      - BACKEND_SERVICE_URL=http://localhost:5000
    depends_on:
      - backend

  dynamodb:
    image: amazon/dynamodb-local:latest
    container_name: dynamodb
    ports:
      - "8000:8000"
    volumes:
      - data:/home/dynamodblocal/data
    command: -jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data

volumes:
  data: {}
